### ISSUE TITLE
Any chance of an event on track load?

### ISSUE THREAD

**Issue by SDenman** [matswainson/vue-soundcloud-player#7]
Hi,
Thanks for this.
This is not really an issue, but it would be neat if the player could emit an event when the track is loaded so we could display a spinner while loading and cancel it when ready.
Can sometimes take a while I find.

Cheers
Simon.

**Comment by matswainson** [comment]
Hi Simon

I have updated the package to version 1.2.0, the player now emits a ready event once loaded.

The readme is updated with an example of usage.

**Comment by SDenman** [comment]
Fantastic!
Thank you so much!
Simon
